openapi: 3.0.0
info:
  title:  Review System API
  version: 1.0.0
  description: API specifications for managing service provider reviews and ratings

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/reviews:
    post:
      summary: Create a new review
      description: Submit a review for a completed service
      tags:
        - Reviews
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewCreate'
            example:
              bookingId: "123e4567-e89b-12d3-a456-426614174000"
              providerId: "987fcdeb-51a2-43f7-9876-543210abcdef"
              rating: 4.5
              comment: "Great service! Very professional and punctual."
              aspects:
                professionalism: 5
                punctuality: 4
                cleanliness: 4.5
              images:
                - "data:image/jpeg;base64,/9j/4AAQSkZJRg..."
      responses:
        '201':
          description: Review created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/providers/{providerId}/reviews:
    get:
      summary: Get provider reviews
      description: Retrieve all reviews for a specific service provider
      tags:
        - Reviews
      parameters:
        - name: providerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The unique identifier of the service provider
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
          description: Number of reviews per page
        - name: sortBy
          in: query
          schema:
            type: string
            enum: [date, rating]
            default: date
          description: Sort reviews by date or rating
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Sort order
      responses:
        '200':
          description: Reviews retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewList'
        '404':
          description: Provider not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/reviews/{reviewId}:
    put:
      summary: Update a review
      description: Modify an existing review
      tags:
        - Reviews
      security:
        - BearerAuth: []
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The unique identifier of the review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewUpdate'
            example:
              rating: 4.0
              comment: "Updated: Service was good but could improve on timing"
              aspects:
                professionalism: 4
                punctuality: 3
                cleanliness: 4
      responses:
        '200':
          description: Review updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User can only update their own reviews
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Delete a review
      description: Remove an existing review
      tags:
        - Reviews
      security:
        - BearerAuth: []
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The unique identifier of the review to delete
      responses:
        '204':
          description: Review deleted successfully (No content)
        '400':
          description: Invalid review ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User can only delete their own reviews
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ReviewCreate:
      type: object
      required:
        - bookingId
        - providerId
        - rating
      properties:
        bookingId:
          type: string
          format: uuid
          description: ID of the completed booking
        providerId:
          type: string
          format: uuid
          description: ID of the service provider
        rating:
          type: number
          minimum: 1
          maximum: 5
          description: Overall rating (1-5)
        comment:
          type: string
          maxLength: 1000
          description: Review comment
        aspects:
          type: object
          description: Specific aspects of the service
          properties:
            professionalism:
              type: number
              minimum: 1
              maximum: 5
            punctuality:
              type: number
              minimum: 1
              maximum: 5
            cleanliness:
              type: number
              minimum: 1
              maximum: 5
        images:
          type: array
          items:
            type: string
            format: byte
          maxItems: 5
          description: Base64 encoded images

    ReviewUpdate:
      type: object
      properties:
        rating:
          type: number
          minimum: 1
          maximum: 5
        comment:
          type: string
          maxLength: 1000
        aspects:
          type: object
          properties:
            professionalism:
              type: number
              minimum: 1
              maximum: 5
            punctuality:
              type: number
              minimum: 1
              maximum: 5
            cleanliness:
              type: number
              minimum: 1
              maximum: 5

    ReviewResponse:
      type: object
      properties:
        reviewId:
          type: string
          format: uuid
        bookingId:
          type: string
          format: uuid
        providerId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        rating:
          type: number
        comment:
          type: string
        aspects:
          type: object
          properties:
            professionalism:
              type: number
            punctuality:
              type: number
            cleanliness:
              type: number
        images:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ReviewList:
      type: object
      properties:
        totalReviews:
          type: integer
        averageRating:
          type: number
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/ReviewResponse'
        pagination:
          type: object
          properties:
            currentPage:
              type: integer
            totalPages:
              type: integer
            limit:
              type: integer

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT